# Generated by Django 4.0.4 on 2022-05-07 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_groupstudents_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudents',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studentgroup', to='user.group'),
        ),
    ]
