# Generated by Django 4.0.4 on 2022-05-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_level_request_groupstudents_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupstudents',
            unique_together={('group', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('professor', 'student')},
        ),
    ]
