# Generated by Django 4.0.4 on 2022-05-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_level_request_groupstudents_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstudents',
            options={'verbose_name': 'Students Group'},
        ),
    ]
