# Generated by Django 4.0.4 on 2022-05-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_groupstudents_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.group')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'unique_together': {('student', 'professor')},
            },
        ),
        migrations.DeleteModel(
            name='GroupStudents',
        ),
    ]
