# Generated by Django 4.0.4 on 2022-05-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_groupstudents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudents',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.group'),
        ),
    ]
