# Generated by Django 4.0.4 on 2022-05-04 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_groupstudents_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('F', 'One'), ('S', 'Two'), ('T', 'Three')], default='S', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professor')),
            ],
        ),
    ]
