# Generated by Django 4.0.4 on 2022-05-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_professor_student_delete_groupstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], default='2', max_length=1),
        ),
    ]
