# Generated by Django 4.0.4 on 2022-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='level',
            field=models.CharField(choices=[('F', 'One'), ('S', 'Two'), ('T', 'Three')], default='S', max_length=1),
        ),
    ]
