# Generated by Django 4.0.4 on 2022-05-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_professor_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor_level',
            old_name='Professor',
            new_name='professor',
        ),
        migrations.AlterUniqueTogether(
            name='professor_level',
            unique_together={('professor', 'level')},
        ),
    ]
