# Generated by Django 4.0.4 on 2022-05-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_group_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('F', 'One'), ('S', 'Two'), ('T', 'Three')], default='S', max_length=1),
        ),
    ]
