# Generated by Django 4.0.4 on 2022-05-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_group_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor_student',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_student', to='user.student'),
        ),
    ]
