# Generated by Django 4.0.4 on 2022-05-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_professor_professor_level_professor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstudents',
            options={'verbose_name': ('Students Group',)},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'professor')},
        ),
        migrations.AlterUniqueTogether(
            name='groupstudents',
            unique_together={('student', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('professor', 'student')},
        ),
    ]
