# Generated by Django 4.0.4 on 2022-05-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_groupstudents_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstudents',
            options={'verbose_name': ('Students Group',), 'verbose_name_plural': 'Students Groups'},
        ),
    ]
