# Generated by Django 4.0.4 on 2022-05-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_groupstudents_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor_level',
            options={'verbose_name': ('Professor Level',), 'verbose_name_plural': 'Professor Levels'},
        ),
    ]
