# Generated by Django 4.0.4 on 2022-05-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_student_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Professor')], default='P', max_length=10),
        ),
    ]
