# Generated by Django 4.0.4 on 2022-05-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_professor_level_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudents',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studentgroup', to='user.group'),
        ),
        migrations.AlterField(
            model_name='groupstudents',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
