# Generated by Django 4.0.4 on 2022-06-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_professorproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfessorProxy',
        ),
        migrations.CreateModel(
            name='ProfessorList',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='ProfessorRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='StudentsList',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
        ),
    ]
