# Generated by Django 4.0.4 on 2022-05-14 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_group_level'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.professor'),
        ),
    ]
