# Generated by Django 4.0.4 on 2022-05-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chapter'),
        ('exam', '0003_exam_chapter_alter_examoptions_chapter'),
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Chapter',
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.chapter'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
