# Generated by Django 4.0.4 on 2022-05-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_groupstudents_options_and_more'),
        ('question_bank', '0002_alter_chapter_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='user.professor'),
        ),
    ]
