# Generated by Django 4.0.4 on 2022-05-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_group_level'),
        ('exam', '0002_alter_exam_chapter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examgroups',
            unique_together={('exam', 'group')},
        ),
    ]
