# Generated by Django 4.0.4 on 2022-05-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chapter'),
        ('exam', '0002_alter_result_unique_together_examgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='user.chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examoptions',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.chapter'),
        ),
    ]
