# Generated by Django 4.0.4 on 2022-05-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_chapter_alter_examoptions_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='level',
        ),
    ]
