# Generated by Django 4.0.4 on 2022-05-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_examgroups_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examgroups',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.exam'),
        ),
    ]
