# Generated by Django 4.0.4 on 2022-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_examgroups_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
